#define JPEG_LIB_VERSION  62
#define LIBJPEG_TURBO_VERSION  2.1.5
#define LIBJPEG_TURBO_VERSION_NUMBER  2001005

//#define C_ARITH_CODING_SUPPORTED
//#define D_ARITH_CODING_SUPPORTED
#define NO_GETENV
#define NO_PUTENV
#define MEM_SRCDST_SUPPORTED
#define WITH_SIMD 1
#define BITS_IN_JSAMPLE  8      /* use 8 or 12 */

#undef RIGHT_SHIFT_IS_UNSIGNED

#define JDCT_DEFAULT JDCT_FASTEST
