/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.7.0
 *
 * Project: 'dashcam.debug+HP' 
 * Target:  'debug+HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HP.h"

/* AlifSemiconductor::BSP:External peripherals:CAMERA Sensor ARX3A0@1.3.0 */
#define RTE_Drivers_CAMERA_SENSOR_ARX3A0   1           /* Driver CAMERA Sensor */
/* AlifSemiconductor::Device:Power Management@1.3.0 */
#define RTE_PM   1           /* Power Management */
/* AlifSemiconductor::Device:SOC Peripherals:CPI@1.3.0 */
#define RTE_Drivers_CPI   1           /* Driver CAMERA Controller */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:I2C@1.3.0 */
#define RTE_Drivers_I2C   1           /* Driver I2C */
/* AlifSemiconductor::Device:SOC Peripherals:LPTIMER@1.3.0 */
#define RTE_Drivers_LPTIMER   1           /* Driver LPTIMER */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@1.3.0 */
#define RTE_Drivers_MIPI_CSI2   1   /* Driver MIPI CSI2 */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@1.3.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   1   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:RTC@1.3.0 */
#define RTE_Drivers_RTC   1           /* Driver RTC */
/* AlifSemiconductor::Device:SOC Peripherals:SDMMC@1.3.0 */
#define RTE_Drivers_SD   1           /* Driver SD */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */


#endif /* RTE_COMPONENTS_H */
